
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL || 'https://dixmxlukmonjgkphakxc.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeG14bHVrbW9uamdrcGhha3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0OTIzMjgsImV4cCI6MjA4MjA2ODMyOH0.fHdiagrBMaS9NdII13CnSYR96icotrG2syewdSGGV94';

export const isConfigured = supabaseUrl.length > 10 && supabaseAnonKey.length > 10;

export const supabase = isConfigured 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

export const DATABASE_SQL = `
-- ==========================================
-- ส่วนที่ 1: ตารางหลักและระบบบันทึกพื้นฐาน
-- ==========================================

CREATE TABLE IF NOT EXISTS schools (
  id TEXT PRIMARY KEY, 
  name TEXT NOT NULL,
  district TEXT, 
  province TEXT, 
  lat DOUBLE PRECISION, 
  lng DOUBLE PRECISION, 
  radius INTEGER DEFAULT 500,
  late_time_threshold TEXT DEFAULT '08:30', 
  academic_year_start TEXT DEFAULT '05-16', 
  academic_year_end TEXT DEFAULT '03-31',
  logo_base_64 TEXT, 
  is_suspended BOOLEAN DEFAULT FALSE, -- เพิ่มคอลัมน์ระงับโรงเรียน
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ตารางเก็บค่าตั้งค่าเฉพาะโรงเรียน (System Config)
CREATE TABLE IF NOT EXISTS school_configs (
  school_id TEXT PRIMARY KEY REFERENCES schools(id) ON DELETE CASCADE,
  drive_folder_id TEXT,
  script_url TEXT,
  telegram_bot_token TEXT,
  app_base_url TEXT,
  official_garuda_base_64 TEXT,
  director_signature_base_64 TEXT,
  director_signature_scale DOUBLE PRECISION DEFAULT 1.0,
  director_signature_y_offset INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  name TEXT NOT NULL, 
  password TEXT NOT NULL, 
  position TEXT, 
  roles TEXT[] DEFAULT '{TEACHER}',
  signature_base64 TEXT, 
  telegram_chat_id TEXT, 
  is_suspended BOOLEAN DEFAULT FALSE, -- เพิ่มคอลัมน์ระงับครู
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  category TEXT DEFAULT 'INCOMING', 
  book_number TEXT NOT NULL, 
  title TEXT NOT NULL, 
  description TEXT,
  "from" TEXT, 
  date DATE DEFAULT CURRENT_DATE, 
  timestamp TEXT, 
  priority TEXT DEFAULT 'Normal',
  attachments JSONB DEFAULT '[]'::jsonb, 
  status TEXT DEFAULT 'PendingDirector', 
  director_command TEXT,
  director_signature_date TEXT,
  signed_file_url TEXT,
  assigned_vice_director_id TEXT,
  vice_director_command TEXT,
  vice_director_signature_date TEXT,
  target_teachers TEXT[] DEFAULT '{}'::text[], 
  acknowledged_by TEXT[] DEFAULT '{}'::text[], 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  teacher_id TEXT, 
  teacher_name TEXT, 
  teacher_position TEXT, 
  type TEXT, 
  start_date DATE NOT NULL, 
  end_date DATE NOT NULL,
  reason TEXT, 
  mobile_phone TEXT, 
  status TEXT DEFAULT 'Pending', 
  director_signature TEXT, 
  approved_date TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_accounts (
  id TEXT PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  name TEXT NOT NULL, 
  type TEXT DEFAULT 'Budget', 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS finance_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  account_id TEXT, 
  date DATE DEFAULT CURRENT_DATE, 
  description TEXT, 
  amount DOUBLE PRECISION DEFAULT 0, 
  type TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  teacher_id TEXT, 
  teacher_name TEXT, 
  date DATE DEFAULT CURRENT_DATE, 
  check_in_time TEXT, 
  check_out_time TEXT, 
  status TEXT, 
  coordinate JSONB, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS director_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  date DATE NOT NULL,
  start_time TEXT,
  end_time TEXT,
  location TEXT,
  created_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plan_projects (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  department_name TEXT,
  name TEXT NOT NULL,
  subsidy_budget DOUBLE PRECISION DEFAULT 0,
  learner_dev_budget DOUBLE PRECISION DEFAULT 0,
  actual_expense DOUBLE PRECISION,
  status TEXT DEFAULT 'Draft',
  fiscal_year TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS budget_settings (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  fiscal_year TEXT,
  subsidy DOUBLE PRECISION DEFAULT 0,
  learner DOUBLE PRECISION DEFAULT 0
);

CREATE TABLE IF NOT EXISTS academic_enrollments (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT NOT NULL,
  levels JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS academic_test_scores (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT NOT NULL,
  test_type TEXT NOT NULL,
  results JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
`;
