
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.SUPABASE_URL || 'https://dixmxlukmonjgkphakxc.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeG14bHVrbW9uamdrcGhha3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0OTIzMjgsImV4cCI6MjA4MjA2ODMyOH0.fHdiagrBMaS9NdII13CnSYR96icotrG2syewdSGGV94';

export const isConfigured = supabaseUrl.length > 10 && supabaseAnonKey.length > 10;

export const supabase = isConfigured 
  ? createClient(supabaseUrl, supabaseAnonKey) 
  : null;

export const DATABASE_SQL = `
-- ==========================================
-- 0. ระบบความปลอดภัยสูงสุด
-- ==========================================
CREATE TABLE IF NOT EXISTS super_admins (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL
);

INSERT INTO super_admins (username, password) 
VALUES ('admin', 'schoolos')
ON CONFLICT (username) DO NOTHING;

-- ==========================================
-- 1. ตารางพื้นฐานระบบ (ข้อมูลโรงเรียนและบุคลากร)
-- ==========================================

-- ตารางโรงเรียน
CREATE TABLE IF NOT EXISTS schools (
  id TEXT PRIMARY KEY, -- รหัสโรงเรียน 8 หลัก
  name TEXT NOT NULL,
  district TEXT,
  province TEXT,
  logo_base_64 TEXT,
  lat FLOAT,
  lng FLOAT,
  radius INTEGER DEFAULT 500,
  late_time_threshold TEXT DEFAULT '08:30',
  is_suspended BOOLEAN DEFAULT FALSE
);

-- ตารางโปรไฟล์ผู้ใช้งาน (Profiles)
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, -- เลขบัตรประชาชน
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  password TEXT DEFAULT '123456',
  position TEXT,
  roles TEXT[] DEFAULT '{TEACHER}',
  signature_base_64 TEXT,
  telegram_chat_id TEXT,
  is_suspended BOOLEAN DEFAULT FALSE,
  is_approved BOOLEAN DEFAULT TRUE
);

-- ==========================================
-- 2. ตารางระบบงานสารบรรณและการเงิน
-- ==========================================

-- ตารางงานสารบรรณ
CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  category TEXT, -- 'INCOMING' | 'ORDER'
  book_number TEXT,
  title TEXT,
  description TEXT,
  from TEXT,
  date DATE,
  timestamp TEXT,
  priority TEXT,
  attachments JSONB DEFAULT '[]',
  status TEXT DEFAULT 'PendingDirector',
  director_command TEXT,
  director_signature_date TEXT,
  signed_file_url TEXT,
  assigned_vice_director_id TEXT,
  vice_director_command TEXT,
  vice_director_signature_date TEXT,
  target_teachers TEXT[] DEFAULT '{}',
  acknowledged_by TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ตารางบันทึกเวลาทำงาน
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  teacher_id TEXT,
  teacher_name TEXT,
  date DATE NOT NULL,
  check_in_time TEXT,
  check_out_time TEXT,
  status TEXT,
  coordinate JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ตารางโครงการและแผนปฏิบัติการ
CREATE TABLE IF NOT EXISTS plan_projects (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  department_name TEXT,
  name TEXT,
  subsidy_budget FLOAT DEFAULT 0,
  learner_dev_budget FLOAT DEFAULT 0,
  actual_expense FLOAT DEFAULT 0,
  status TEXT DEFAULT 'Draft',
  fiscal_year TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ปรับปรุงตาราง budget_settings เพื่อรองรับ flag
CREATE TABLE IF NOT EXISTS budget_settings (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  fiscal_year TEXT,
  subsidy FLOAT DEFAULT 0,
  learner FLOAT DEFAULT 0,
  allow_teacher_proposal BOOLEAN DEFAULT FALSE -- เพิ่มฟิลด์นี้
);

-- ตารางรายการเงิน
CREATE TABLE IF NOT EXISTS finance_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  account_id TEXT,
  date DATE NOT NULL,
  description TEXT,
  amount FLOAT NOT NULL,
  type TEXT -- 'Income' | 'Expense'
);

CREATE TABLE IF NOT EXISTS finance_accounts (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT -- 'Budget' | 'NonBudget' | 'Coop'
);


-- ==========================================
-- 3. ตารางระบบงานวิชาการและการลา
-- ==========================================

CREATE TABLE IF NOT EXISTS leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  teacher_id TEXT, 
  teacher_name TEXT, 
  teacher_position TEXT, 
  type TEXT, 
  start_date DATE NOT NULL, 
  end_date DATE NOT NULL,
  start_time TEXT, 
  end_time TEXT,   
  substitute_name TEXT, 
  reason TEXT, 
  mobile_phone TEXT, 
  contact_info TEXT, 
  status TEXT DEFAULT 'Pending', 
  director_signature TEXT, 
  approved_date TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS school_configs (
  school_id TEXT PRIMARY KEY REFERENCES schools(id) ON DELETE CASCADE,
  drive_folder_id TEXT,
  script_url TEXT,
  telegram_bot_token TEXT,
  app_base_url TEXT,
  official_garuda_base_64 TEXT,
  director_signature_base_64 TEXT,
  director_signature_scale FLOAT DEFAULT 1.0,
  director_signature_y_offset INTEGER DEFAULT 0,
  officer_department TEXT,
  internal_departments text[] DEFAULT '{}',
  external_agencies text[] DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS academic_enrollments (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT,
  levels JSONB DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS academic_test_scores (
  id TEXT PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT,
  test_type TEXT,
  results JSONB DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS academic_calendar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT,
  title TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS academic_sar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id TEXT REFERENCES schools(id) ON DELETE CASCADE,
  year TEXT NOT NULL,
  type TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
`;
